export enum AppFeatureType {
  AppFeatureBoardView = 'AppFeatureBoardView',
  AppFeatureIntegration = 'AppFeatureIntegration',
  AppFeatureSolution = 'AppFeatureSolution',
  AppFeatureItemView = 'AppFeatureItemView',
  AppFeatureDashboardWidget = 'AppFeatureDashboardWidget',
  AppFeatureAccountSettingsView = 'AppFeatureAccountSettingsView',
  AppFeatureDocActions = 'AppFeatureDocActions',
  AppFeatureObject = 'AppFeatureObject',
  AppFeatureWorkspaceView = 'AppFeatureWorkspaceView',
  AppFeatureAI = 'AppFeatureAI',
  AppFeatureAiBoardMainMenuHeader = 'AppFeatureAiBoardMainMenuHeader',
  AppFeatureAiItemUpdateActions = 'AppFeatureAiItemUpdateActions',
  AppFeatureAiDocSlashCommand = 'AppFeatureAiDocSlashCommand',
  AppFeatureAiDocContextualMenu = 'AppFeatureAiDocContextualMenu',
  AppFeatureAiDocQuickStart = 'AppFeatureAiDocQuickStart',
  AppFeatureAiDocTopBar = 'AppFeatureAiDocTopBar',
  AppFeatureColumnTemplate = 'AppFeatureColumnTemplate',
  AppFeatureAiIcAssistantHelpCenter = 'AppFeatureAiIcAssistantHelpCenter',
  AppFeatureAppWizard = 'AppFeatureAppWizard',
  AppFeatureGroupMenuAction = 'AppFeatureGroupMenuAction',
  AppFeatureItemMenuAction = 'AppFeatureItemMenuAction',
  AppFeatureNotificationKind = 'AppFeatureNotificationKind',
  AppFeatureNotificationSettingKind = 'AppFeatureNotificationSettingKind',
  AppFeatureBlock = 'AppFeatureBlock',
  AppFeatureItemBatchAction = 'AppFeatureItemBatchAction',
  AppFeatureAiFormula = 'AppFeatureAiFormula',
  AppFeatureAiItemEmailsAndActivitiesActions = 'AppFeatureAiItemEmailsAndActivitiesActions',
  AppFeatureAiEmailsAndActivitiesHeaderActions = 'AppFeatureAiEmailsAndActivitiesHeaderActions',
  AppFeatureFieldType = 'AppFeatureFieldType',
  AppFeatureProduct = 'AppFeatureProduct',
  AppFeatureProductView = 'AppFeatureProductView',
  AppFeatureBoardColumnAction = 'AppFeatureBoardColumnAction',
  AppFeatureBoardColumnExtension = 'AppFeatureBoardColumnExtension',
  AppFeaturePackagedBlock = 'AppFeaturePackagedBlock',
  AppFeatureTopbar = 'AppFeatureTopbar',
  AppFeatureWorkflowTemplate = 'AppFeatureWorkflowTemplate',
  AppFeatureColumn = 'AppFeatureColumn',
  AppFeatureSubWorkflow = 'AppFeatureSubWorkflow',
  AppFeatureBoardHeaderAction = 'AppFeatureBoardHeaderAction',
  AppFeatureDialog = 'AppFeatureDialog',
  AppFeatureDataEntity = 'AppFeatureDataEntity',
  AppFeatureSurfaceView = 'AppFeatureSurfaceView',
}

export enum MondayAppsToolCategory {
  APP = 'app',
  APP_VERSION = 'app_version',
  APP_FEATURE = 'app_feature',
  STORAGE = 'storage',
  MONDAY_CODE = 'monday_code',
}
